apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kafka-connect-metrics
  namespace: infrastructure
  labels:
    component: main # must match with the serviceMonitorSelector
spec:
  selector:
    matchLabels: # must match with the Service labels (metadata)
      strimzi.io/cluster: debezium-connect-cluster
      strimzi.io/kind: KafkaConnect
  namespaceSelector:
    matchNames:
      - infrastructure
  endpoints:
    - port: tcp-prometheus
      path: /metrics
      interval: 30s