apiVersion: v1
kind: Service
metadata:
  name: kafka-connect-prometheus
  namespace: infrastructure
  labels: # must match with the "spec.selector.matchLabels" in the ServiceMonitor
    strimzi.io/cluster: debezium-connect-cluster
    strimzi.io/kind: KafkaConnect
spec:
  type: ClusterIP
  selector: # must match with the labels in Deployment type (pod)
    strimzi.io/cluster: debezium-connect-cluster
    strimzi.io/kind: KafkaConnect
  ports:
    - name: tcp-prometheus
      port: 9404
      targetPort: tcp-prometheus
      protocol: TCP