{
 "title": "Flink Monitoring",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Current Uptime (minutes)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "flink_jobmanager_job_uptime{job_name=\"Merge_streams\"} / 60000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Restart Times",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "flink_jobmanager_job_numRestarts{job_name=\"Merge_streams\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed Checkpoints",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "flink_jobmanager_job_numberOfFailedCheckpoints{job_name='Merge_streams'}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Completed Checkpoints",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "flink_jobmanager_job_numberOfCompletedCheckpoints{job_name='Merge_streams'}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Task Slots",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "flink_jobmanager_taskSlotsTotal",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Task Slots Available",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "flink_jobmanager_taskSlotsAvailable",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Input Rate (records/sec)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum(rate(flink_taskmanager_job_task_numRecordsIn{job_name='Merge_streams'}[5m])) by (task_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Completed and Failed Checkpoints Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "rate(flink_jobmanager_job_numberOfCompletedCheckpoints{job_name='Merge_streams'}[5m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(flink_jobmanager_job_numberOfFailedCheckpoints{job_name='Merge_streams'}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Checkpoint Size (MB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "avg_over_time(flink_jobmanager_job_lastCheckpointSize{job_name='Merge_streams'}[1h]) / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Checkpoint Duration (seconds)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "avg_over_time(flink_jobmanager_job_lastCheckpointDuration{job_name='Merge_streams'}[1h]) / 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "sum(rate(flink_taskmanager_Status_JVM_CPU_Load[5m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(flink_jobmanager_Status_JVM_CPU_Load[5m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}