{
 "title": "Kafka Cluster Monitoring",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Offline Partitions",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(kafka_controller_kafkacontroller_offlinepartitionscount) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Under Partition Replication",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(kafka_cluster_partition_underreplicated) by (topic)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consumer Group Lag",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_lag) by (consumergroup)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Messages In Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(rate(kafka_server_brokertopicmetrics_messagesin_total{topic=\"test.public.raw_item_metadata\"}[5m])) by (topic)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(kafka_server_brokertopicmetrics_messagesin_total{topic=\"test.public.raw_reviews\"}[5m])) by (topic)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(kafka_server_brokertopicmetrics_messagesin_total{topic=\"merge_metadata_reviews\"}[5m])) by (topic)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bytes Out Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(kafka_server_brokertopicmetrics_bytesout_total{topic=\"test.public.raw_item_metadata\"}[5m])) by (topic)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(kafka_server_brokertopicmetrics_bytesout_total{topic=\"test.public.raw_reviews\"}[5m])) by (topic)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bytes In Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum(rate(kafka_server_brokertopicmetrics_bytesin_total{topic=\"test.public.raw_item_metadata\"}[5m])) by (topic)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(kafka_server_brokertopicmetrics_bytesin_total{topic=\"test.public.raw_reviews\"}[5m])) by (topic)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(kafka_server_brokertopicmetrics_bytesin_total{topic=\"merge_metadata_reviews\"}[5m])) by (topic)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Kafka Connect Producer Record Error",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "rate(kafka_producer_topic_record_error_total{clientid=~\".*debezium.*\", topic='test.public.raw_item_metadata'}[5m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(kafka_producer_topic_record_error_total{clientid=~\".*debezium.*\", topic='test.public.raw_reviews'}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Kafka Connect Producer Byte Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "rate(kafka_producer_topic_byte_total{clientid=~\".*debezium.*\", topic='test.public.raw_item_metadata'}[5m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(kafka_producer_topic_byte_total{clientid=~\".*debezium.*\", topic='test.public.raw_reviews'}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Kafka Connect S3 Sink Record",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "rate(kafka_connect_sink_task_sink_record_send_rate{connector='debezium-connector-s3'}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Kafka Connect Producer Record Send",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "rate(kafka_producer_topic_record_send_total{clientid=~\".*debezium.*\", topic='test.public.raw_item_metadata'}[5m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(kafka_producer_topic_record_send_total{clientid=~\".*debezium.*\", topic='test.public.raw_reviews'}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Tasks Retries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": "sum(kafka_connect_task_error_total_retries) by (connector)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Tasks Error",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "sum(kafka_connect_task_error_total_errors_logged) by (connector)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}