apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: {{ .Values.spark.namespace }}
  name: spark-submit-binding
subjects:
- kind: ServiceAccount
  name: default
  namespace: {{ .Values.airflow.namespace }}
- kind: ServiceAccount
  name: airflow-worker
  namespace: {{ .Values.airflow.namespace }}
- kind: ServiceAccount
  name: default
  namespace: {{ .Values.jenkins.namespace }}
roleRef:
  kind: Role
  name: spark-submit-role
  apiGroup: rbac.authorization.k8s.io