apiVersion: v2
name: Storage Configuration
description: Postgres and Minio Configuration
type: application
version: 0.1.0
appVersion: "1.0.0"
maintainers:
  - email: longpham1801@gmail.com
    name: longpk1