apiVersion: v1
kind: Service
metadata:
  name: flink-prometheus
  namespace: processor
  labels: # must match with the "spec.selector.matchLabels" in the ServiceMonitor
    app: flink-merge-streams
    type: flink-native-kubernetes
spec:
  type: ClusterIP
  selector: # must match with the labels in Deployment type (pod)
    app: flink-merge-streams
    type: flink-native-kubernetes
  ports:
    - name: tcp-prometheus
      port: 9249
      targetPort: 9249
      protocol: TCP