apiVersion: v1
kind: Service
metadata:
  name: spark-history-server
  namespace: processor
spec:
  type: ClusterIP
  selector:
    app: spark-history-server
  ports:
    - name: spark-history-server
      protocol: TCP
      port: 18080
      targetPort: 18080