apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: spark-adding-uuidv7
  namespace: processor
spec:
  type: Python
  pythonVersion: "3"
  mode: cluster
  image: longpk1/spark_processing:1.1.2
  imagePullPolicy: Always
  mainApplicationFile: local:///opt/spark/work-dir/adding_uuidv7.py
  sparkVersion: 3.4.3
  driver:
    cores: 1
    # memory: 4096m
    memory: 1g  # Increased from 4Gi to 8Gi
    # memory: 2g  # Increased from 4Gi to 8Gi
    labels:
      version: 3.4.3
    serviceAccount: spark-operator-controller
    # serviceAccount: spark-processing-sa
    env:
      - name: ENDPOINT
        value: minio-svc.infrastructure.svc.cluster.local:9000
      - name: ACCESS_KEY
        valueFrom:
          secretKeyRef:
            name: minio-credentials
            key: access-key
      - name: SECRET_KEY
        valueFrom:
          secretKeyRef:
            name: minio-credentials
            key: secret-key
      - name: BUCKET_NAME
        value: amazonreviews
      - name: RAW_DATA_FOLDER
        value: historical-raw-data
      - name: DELTA_DATA_FOLDER
        value: historical-delta-format-data
      - name: MERGE_DATA_FOLDER
        value: merge-data
      - name: STREAMING_DATA_FOLDER
        value: streaming-data
      - name: REVIEW_SCHEMA_TOPIC
        value: review
      - name: METADATA_SCHEMA_TOPIC
        value: metadata
      - name: SCHEMA_REGISTRY_ENDPOINT
        value: http://schema-registry-svc.infrastructure.svc.cluster.local:8081
  executor:
    # instances: 3
    # cores: 4
    # memory: 1024m
    instances: 1  # Increased from 3 to 4
    cores: 1
    memory: 1g  # Increased from 1Gi to 6Gi
    # memory: 1g  # Increased from 1Gi to 6Gi
    labels:
      version: 3.4.3
    env:
      - name: ENDPOINT
        value: minio-svc.infrastructure.svc.cluster.local:9000
      - name: ACCESS_KEY
        valueFrom:
          secretKeyRef:
            name: minio-credentials
            key: access-key
      - name: SECRET_KEY
        valueFrom:
          secretKeyRef:
            name: minio-credentials
            key: secret-key
      - name: BUCKET_NAME
        value: amazonreviews
      - name: RAW_DATA_FOLDER
        value: historical-raw-data
      - name: DELTA_DATA_FOLDER
        value: historical-delta-format-data
      - name: MERGE_DATA_FOLDER
        value: merge-data
      - name: STREAMING_DATA_FOLDER
        value: streaming-data
      - name: REVIEW_SCHEMA_TOPIC
        value: review
      - name: METADATA_SCHEMA_TOPIC
        value: metadata
      - name: SCHEMA_REGISTRY_ENDPOINT
        value: http://schema-registry-svc.infrastructure.svc.cluster.local:8081
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                spark-role: executor
                spark-app-name: amazon-reviews-batching
                sparkoperator.k8s.io/app-name: spark-adding-uuidv7
            topologyKey: kubernetes.io/hostname