apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: spark-raw2delta-avro # configmap (name)
  namespace: processor
spec:
  type: Python
  pythonVersion: "3"
  mode: cluster
  image: longpk1/spark_processing_datamart_optimize:1.5.2
  imagePullPolicy: Always
  mainApplicationFile: local:///opt/spark/work-dir/convert_raw2delta_avro_v2.py
  sparkVersion: 3.4.3
  sparkConf:
    "spark.eventLog.enabled": "true"
    "spark.eventLog.compress": "true"
    "spark.eventLog.dir": "s3a://spark-events/spark-eventlog/"

    "spark.sql.files.maxPartitionBytes": "256m"
    "spark.sql.adaptive.enabled": "true"
    "spark.sql.adaptive.coalescePartitions.enabled": "false"

    "spark.hadoop.fs.s3a.endpoint": http://minio-svc.infrastructure.svc.cluster.local:9000
    "spark.hadoop.fs.s3a.path.style.access": "true"
    "spark.hadoop.fs.s3a.connection.ssl.enabled": "false"
    "spark.hadoop.fs.s3a.credentials.provider.class": com.amazonaws.auth.EnvironmentVariableCredentialsProvider
  driver:
    cores: 1
    memory: 4g  # Increased from 4Gi to 8Gi
    labels:
      version: 3.4.3
    serviceAccount: spark-operator-controller
    # serviceAccount: spark-processing-sa
    env:
      - name: ENDPOINT
        value: minio-svc.infrastructure.svc.cluster.local:9000
      - name: ACCESS_KEY
        valueFrom:
          secretKeyRef:
            name: minio-credentials
            key: access-key
      - name: SECRET_KEY
        valueFrom:
          secretKeyRef:
            name: minio-credentials
            key: secret-key
      - name: BUCKET_NAME
        value: amazonreviews
      - name: RAW_DATA_FOLDER
        value: historical-raw-data
      - name: DELTA_DATA_FOLDER
        value: historical-delta-format-data
      - name: MERGE_DATA_FOLDER
        value: merge-data
      - name: STREAMING_DATA_FOLDER
        value: streaming-data
      - name: REVIEW_SCHEMA_TOPIC
        value: review
      - name: METADATA_SCHEMA_TOPIC
        value: metadata
      - name: SCHEMA_REGISTRY_ENDPOINT
        value: http://schema-registry-svc.infrastructure.svc.cluster.local:8081
  executor:
    instances: 2  # Increased from 3 to 4
    cores: 4
    memory: 4g  # Increased from 1Gi to 6Gi
    labels:
      version: 3.4.3
    env:
      - name: ENDPOINT
        value: minio-svc.infrastructure.svc.cluster.local:9000
      - name: ACCESS_KEY
        valueFrom:
          secretKeyRef:
            name: minio-credentials
            key: access-key
      - name: SECRET_KEY
        valueFrom:
          secretKeyRef:
            name: minio-credentials
            key: secret-key
      - name: BUCKET_NAME
        value: amazonreviews
      - name: RAW_DATA_FOLDER
        value: historical-raw-data
      - name: DELTA_DATA_FOLDER
        value: historical-delta-format-data
      - name: MERGE_DATA_FOLDER
        value: merge-data
      - name: STREAMING_DATA_FOLDER
        value: streaming-data
      - name: REVIEW_SCHEMA_TOPIC
        value: review
      - name: METADATA_SCHEMA_TOPIC
        value: metadata
      - name: SCHEMA_REGISTRY_ENDPOINT
        value: http://schema-registry-svc.infrastructure.svc.cluster.local:8081
  monitoring:
    exposeDriverMetrics: true
    exposeExecutorMetrics: true
    prometheus:
      jmxExporterJar: "/opt/spark/jars/jmx_prometheus_javaagent-1.0.1.jar"
      port: 8090