apiVersion: v2
name: Permission
description: Grant permissions for airflow-worker and default service accounts to access the spark and flink resources
type: application
version: 0.1.0
appVersion: "1.0.0"
maintainers:
  - email: longpham1801@gmail.com
    name: longpk1